### ISSUE TITLE
Manage Credentials

### ISSUE THREAD

**Issue by tgpmoraes** [sequenceiq/cloudbreak-docs#155]
Hi,

I am trying to setup Cloudbreak on Azure, and in the part to put: App Id, App Owner Tenant Id, and Password, I am getting a error saying that something is invalid.

One thing that I noticed, that I am not able to get the Tenant ID, I don't know if the name has changed, but I got Object ID. Is the same thing?
![image](https://cloud.githubusercontent.com/assets/8151342/21080279/4b9c491c-bf92-11e6-9612-4f4879292e29.png)
![image](https://cloud.githubusercontent.com/assets/8151342/21080281/504e5018-bf92-11e6-9ab6-e4dd3028ef92.png)

**Comment by mhmxs** [comment]
Hi @tgpmoraes ,

Sorry for the very late answer, and i hope your issue is already solved. In newer version of Cloudbreak we introduced an easier way to create Azure credentials, so any comment is irrelevant now :( really sorry.
