### ISSUE TITLE
Can't SSH into GCP instance created from proposed image

### ISSUE THREAD

**Issue by Pega88** [sequenceiq/cloudbreak-docs#164]
It seems that the setup is not completely correct for GCP (Google Cloud Platform).

I had no issues creating the image (Cloudbreak Deployer GCP Image Details - gcloud compute images create cloudbreak-deployer-163-2017-02-22 --source-uri gs://sequenceiqimage/cloudbreak-deployer-163-2017-02-22.tar.gz
) and starting an instance from it, and since it's on the default network, the default firewall rules apply which opens port 22 and 443. However, there is no way to connect over SSH to the instance created from the cloudbreak-deployer image. With SSH-keys in GCP, I see both 'cloudbreak' as my own name as usernames. 

How to connect to the instance over SSH?

Furthermore, There is a link to Amazon regarding opening the Ports, while this is Google Cloud Platform on 'https://github.com/sequenceiq/cloudbreak-docs/blob/master/docs/gcp/images.md'.

**Comment by mhmxs** [comment]
Hi @Pega88 ,

It is Google's responsible to transfer ssh keys to the host. I launched an instance than logged in with my key and i found all entries (28) in cloudbreak user's authorized_keys. If you are not sure you can use Google's web ui to log in via ssh, so you can check what went wrong. I would close the issue now, but please feel free if you have still issue related to Cloudbreak.
