### ISSUE TITLE
Please add line for minimum system requirement on installation document.

### ISSUE THREAD

**Issue by promiseu77** [sequenceiq/cloudbreak-docs#5]
We need an information regarding minimum system requirement for Cloudbreak environment.

Please provide minimum storage size / CPU / Memory for using Cloudbreak.

Thanks

**Comment by doktoric** [comment]
You can find the minimum system requirement here: http://sequenceiq.com/cloudbreak-docs/master/
Under the 'Installing the Cloudbreak Deployer' section

**Comment by promiseu77** [comment]
Thanks Roichard

**Comment by doktoric** [comment]
your welcome. If you have any other question feel free to ask.
